stages:
  - test
  - build

default:
  tags:
    - fit2107

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - Frontend/.npm/
    - Backend/.cache/pip/

frontend_test_build:
  image: node:22
  stage: test
  timeout: 30m
  script:
    - cd Frontend
    - npm config set cache .npm --global
    - npm install --legacy-peer-deps --prefer-offline --no-audit --progress=false
    - npm run test
    - npm run build
  artifacts:
    paths:
      - Frontend/dist
    expire_in: 1 week

backend_check:
  image: python:3.11
  stage: test
  timeout: 20m
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/Backend/.cache/pip"
  script:
    - cd Backend
    - pip install -e .
    - python -m py_compile app/main.py app/api/schemas/loads.py
